### ISSUE TITLE
Compile Error on Windows 10/11

### ISSUE THREAD

**Issue by eli-temanson** [sesps/SPS_SABRE_EventBuilder#6]
root version: 6.26/10

[error.txt](https://github.com/sesps/SPS_SABRE_EventBuilder/files/10951999/error.txt)

**Comment by eli-temanson** [comment]
The issue is likely that the root dictionary generator isn't working.

**Comment by gwm17** [comment]
This is interesting, looks like maybe some kind of compiler mismatch between ROOT and Windows where they expect features that don't exist. I'll run some tests and see if there is anything we can do about it

**Comment by gwm17** [comment]
Issue resolved, no fixes needed.
