### ISSUE TITLE
Plotting Question in SFPPlotter.cpp

### ISSUE THREAD

**Issue by jce10** [sesps/SPS_SABRE_EventBuilder#7]
In line 57 where it makes the X1 both planes histogram with no cuts, the code reads

MyFill(table,"x1NoCuts_bothplanes",600,-300,300,ev.x2);

I think it should be,

MyFill(table,"x1NoCuts_bothplanes",600,-300,300,ev.x1);

since you're making X1. I could be wrong but thought I'd let you know!

**Comment by gwm17** [comment]
Good catch! Fixed and pushed to main.
